version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db_docker
    environment:
      POSTGRES_DB: wdm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  springboot:
    build: .
    container_name: WahenoorDigitalMedia
    environment:
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: wdm
      DB_USER: postgres
      DB_PASSWORD: root
    ports:
      - "8282:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: